### PR TITLE
Restrict SSH access to GDS IPs

### PR DESCRIPTION
**Pull request by andreagrandi**
This change restricts the SSH access to EC2 instances created by the Terraform script, only to GDS IPs. The list has been taken from https://sites.google.com/a/digital.cabinet-office.gov.uk/gds-internal-it/news/aviationhouse-sourceipaddresses?pli=1

### CODE REVIEW

**Comment by bleach** [comment]
I think the group should be renamed from "allow_all_ssh" now.

**Comment by ivyleavedtoadflax** [comment]
Sure this is the case - but just checking - we will still have access using the VPN?

**Comment by andreagrandi** [comment]
@ivyleavedtoadflax that's my understanding, but it's hard to test from the office. I can test this evening from home.

**Comment by ivyleavedtoadflax** [comment]
Take note @ellieking17 and @myst3ria: when you pull next; you will need to be on the VPN to use in future.

**Pull request merged**
